import React, { useState } from 'react';


const survivalKits = {
    tropical: [
      { name: "Mosquito Net", description: "Protects against mosquitoes in humid climates.", image: "/images/m_net.jpg", details: "Mosquito nets create a physical barrier between individuals and mosquitoes, significantly reducing the risk of contracting diseases. Nets are inexpensive compared to medical treatments for mosquito-borne diseases and are a sustainable preventive solution. Unlike chemical repellents, mosquito nets do not release toxins into the environment, making them a safe option for long-term use. By preventing mosquitoes and other insects from disturbing sleep, nets help maintain uninterrupted rest, essential for health and well-being. Lightweight and portable, mosquito nets can be set up easily in a variety of settings, such as homes, campsites, or temporary shelters.", type: "Protection" },
      { name: "Waterproof Bag", description: "Keeps your gear dry in rainy weather.", image: "/images/30_ltr.jpg", details: "Waterproof bags protect essential items, such as electronics, documents, and clothing, from getting wet in rainy or submerged conditions. This ensures that gear remains usable in harsh weather. Help in organizing and compartmentalizing survival gear, making it easier to access items quickly in emergencies. Items like matches, maps, food, and batteries can get ruined if exposed to moisture. Ensure that these items remain functional when needed the most.", type: "Protection" },
      { name: "Sunscreen", description: "Essential to prevent sunburn in hot climates.", image: "/images/Sunscreen.jpg", details: "Sunscreen helps protect the skin from harmful ultraviolet (UV) radiation from the sun. UV rays can cause skin damage, sunburns, and increase the risk of skin cancer over time. Prevents reddening and irritation of the skin caused by overexposure to the sun. Regular use can minimize the risk of painful burns and long-term skin damage. It contain moisturizing ingredients that keep the skin hydrated while protecting it from sun exposure. This is especially important for dry or sensitive skin.", type: "Clothing" },
      { name: "Sun Hat", description: "Shields your face from the sun.", image: "/images/hat.jpg", details: "Light, breathable hat to protect from sun exposure. Provides physical protection from harmful UV rays, reducing exposure to the sun on your face, neck, and ears. This helps lower the risk of sunburn and skin damage caused by UV radiation. scalp is particularly vulnerable to sunburn, but a sun hat protects this area from UV damage. It also prevents hair from drying out or becoming damaged due to prolonged sun exposure. It prevent the body heat escaping through your head.", type: "Protection" },
      { name: "Hydration Pack", description: "Portable hydration system for easy access.", image: "/images/hydration_pack.jpg", details: "Designed for easy drinking on the go during hikes.  Hydration packs allow you to drink water hands-free, thanks to the built-in straw or hose. This makes it easy to stay hydrated while engaging in physical activities like hiking, biking, or running, without needing to stop and remove a water bottle. Staying hydrated is essential for maintaining energy levels, preventing fatigue, and avoiding dehydration. Hydration packs provide a steady and convenient way to drink water during long hikes, runs, or other outdoor activities.", type: "Protection" },
      { name: "Signal Mirror", description: "For signaling help from a distance.", image: "/images/signal_mirror.jpg", details: "Highly reflective mirror to signal rescue teams. It is an essential tool for emergency situations where you need to attract attention from rescuers or others in the vicinity. It can reflect sunlight over long distances, making it visible from miles away. The mirror can reflect sunlight over long distances, allowing you to signal rescue teams, aircraft, or other individuals from far away, which is especially important in vast outdoor environments like forests, mountains, or open seas.", type: "Protection" },
      { name: "Whistle", description: "Alert others or signal distress.", image: "/images/whistle.jpg", details: "A loud whistle to attract attention in case of emergency. Whistle is an essential tool for signaling in emergency situations. Its loud, high-pitched sound can carry over long distances, making it easier to alert others to your presence or call for help.  whistles can be used for a variety of other purposes, such as attracting attention in a group setting, coordinating movement during team activities, or warning of potential dangers.", type: "Protection" },
      { name: "Portable Cooking Stove", description: "Compact stove for cooking meals.", image: "/images/portable_stove.jpg", details: "Portable stove to cook meals during tropical camping or survival situations. Portable cooking stove allows you to cook meals anywhere, whether you’re camping, hiking, or picnicking. It provides a reliable cooking solution when you're away from a kitchen or traditional cooking appliances. These stoves are generally simple to set up and operate. They typically use fuel sources like propane, butane, or liquid fuel, and with just a few simple steps, you can have a cooking system ready to use in the outdoors.", type: "Cooking" },
      { name: "Knife", description: "Knife for cutting and defending.", image: "/images/knife.jpg", details: "Knife is used to cut meat and plants in tropical environment. Knife is one of the most versatile tools in any outdoor or survival kit. It can be used for a wide range of tasks such as cutting rope, building shelter, preparing food, and carving tools or weapons in emergency situations. In emergencies, a knife can be used to cut through clothing to access wounds, open bandages, or prepare a splint for injury stabilization. It’s an essential tool in any first-aid kit for its wide range of medical applications.", type: "Protection" },
    ],
    desert: [
      { name: "Sunscreen", description: "Prevents sunburn from extreme sunlight.", image: "/images/sunscreen1.jpg", details: "Protects your skin from the harsh desert sun. Sunscreen helps protect the skin from harmful ultraviolet (UV) radiation from the sun. UV rays can cause skin damage, sunburns, and increase the risk of skin cancer over time. Prevents reddening and irritation of the skin caused by overexposure to the sun. Regular use can minimize the risk of painful burns and long-term skin damage. It contain moisturizing ingredients that keep the skin hydrated while protecting it from sun exposure. This is especially important for dry or sensitive skin.", type: "Clothing" },
      { name: "Water Bottle", description: "Stay hydrated in dry conditions.", image: "/images/water_bottle.jpg", details: "Insulated water bottle to keep liquids cool. Water bottle is essential for staying hydrated throughout the day, whether you're engaging in outdoor activities, traveling, or simply going about your daily routine. It ensures you have easy access to water whenever you need it. Reusable water bottles are a one-time investment that can save you money in the long run by reducing the need to buy bottled water. Refilling your bottle is much cheaper than continuously purchasing disposable plastic bottles.", type: "Protection" },
      { name: "Wide-brimmed Hat", description: "Shields your face and neck from the sun.", image: "/images/wide_brimmed _hat.jpg", details: "Helps you stay cool and protects from sun exposure. Wide-brimmed hat can provide relief from the heat by shading your face and neck, helping to regulate body temperature and reduce the risk of overheating or heatstroke, especially in hot environments. By providing shade, a wide-brimmed hat helps to keep you cooler in the sun. This can be particularly beneficial during outdoor activities like hiking, gardening, or attending outdoor events.", type: "Clothing" },
      { name: "Desert Boots", description: "Protects your feet from hot sand and rough terrain.", image: "/images/desert_boot.jpg", details: "Sturdy boots designed for desert conditions. Desert boots are designed to provide comfort and support in hot and dry conditions, making them ideal for activities like hiking, trekking, or desert exploration. Their lightweight design and breathable materials help keep your feet cool in extreme heat. Made from materials like suede or canvas, desert boots are highly breathable. This allows air circulation around the feet, preventing excessive sweating and reducing the risk of blisters or foot discomfort in warm climates.", type: "Clothing" },
      { name: "Dust Mask", description: "Prevents inhalation of dust and sand.", image: "/images/dust_mask.jpg", details: "Breathable mask that shields from dust and sand. Dust masks are designed to filter out harmful airborne particles, such as dust, pollen, and pollutants. They help prevent the inhalation of substances that could cause respiratory issues, such as allergies, asthma, or long-term lung damage. Dust masks are typically lightweight and easy to carry, making them convenient for on-the-go use. They can be easily folded or stored in a bag.", type: "Protection" },
      { name: "Signal Mirror", description: "For signaling help from a distance.", image: "/images/signal_mirror.jpg", details: "Reflective mirror for emergency signaling. Highly reflective mirror to signal rescue teams. It is an essential tool for emergency situations where you need to attract attention from rescuers or others in the vicinity. It can reflect sunlight over long distances, making it visible from miles away. The mirror can reflect sunlight over long distances, allowing you to signal rescue teams, aircraft, or other individuals from far away, which is especially important in vast outdoor environments like forests, mountains, or open seas.", type: "Protection" },
      { name: "GPS Device", description: "Accurate location tracking in remote areas.", image: "/images/gps.jpg", details: "Reliable GPS device for navigation in the desert. GPS devices provide real-time, accurate navigation, helping users find their way in unfamiliar areas. They offer turn-by-turn directions, showing routes and alternative paths, making them essential for road trips, hiking, and outdoor exploration. GPS devices often include algorithms for optimizing routes, considering traffic, road conditions, or terrain. They can help you avoid traffic jams, road closures, and other obstacles, saving time and fuel during travel.", type: "Protection" },
      { name: "Cooking Pot", description: "Useful for cooking over a campfire.", image: "/images/tin.jpg", details: "A sturdy pot for cooking food in desert conditions. Cooking pot is an essential tool for preparing a variety of dishes, from boiling water and cooking pasta to simmering stews, soups, and sauces. It can handle many different cooking methods, making it a must-have for most meal preparations.", type: "Cooking" },
      { name: "Sun Glass", description: "Protecting from the sun.", image: "/images/sun_glass.jpg", details: "Sunglasses protect your eyes from harmful ultraviolet (UV) rays from the sun. Prolonged exposure to UV rays can damage the eyes, leading to conditions such as cataracts, macular degeneration, and photokeratitis (sunburn of the cornea). Sunglasses help block out these harmful rays, reducing the risk of eye damage.  Sunglasses act as a barrier against dust, wind, and debris, which can irritate or damage the eyes. They can protect your eyes during outdoor activities such as hiking, biking, or sailing, ensuring comfort and safety in various weather conditions.", type: "Protection" },
    ],
    mountain: [
      { name: "Thermal Blanket", description: "Provides warmth during cold nights.", image: "/images/blanket.jpg", details: "Insulated blanket for staying warm in freezing conditions. Thermal blankets, often made from Mylar or other reflective materials, are designed to trap and retain body heat in emergency situations. They reflect heat back to the body, preventing hypothermia in cold environments by providing a layer of insulation. The reflective surface of thermal blankets reflects up to 90% of your body heat, which helps maintain warmth in cold conditions. This is especially useful in outdoor survival situations where access to shelter or warmth might be limited. Thermal blankets are commonly used by first responders to prevent shock and treat hypothermia.", type: "Clothing" },
      { name: "Climbing Gear", description: "Essential for climbing in rocky terrain.", image: "/images/climbing_gear.jpg", details: "Includes ropes, carabiners, and harnesses. The primary purpose of climbing gear is to ensure safety during climbing activities. Gear like helmets, harnesses, ropes, carabiners, and belay devices are crucial for preventing falls, minimizing injury, and providing support during climbs. n case of an emergency, climbing gear can be used for rescues or self-rescue. Gear like prusik loops, ascenders, and pulleys allows climbers to ascend or descend safely, or to assist others in getting out of challenging situations.", type: "Protection" },
      { name: "First Aid Kit", description: "For treating injuries during hiking or climbing.", image: "/images/first_aid_kit.jpg", details: "Bandages, antiseptics, and pain relief for injuries. Antiseptic solutions, alcohol pads, and sterile wipes are common in first aid kits, helping to disinfect wounds and prevent the development of infections in cuts, scrapes, or puncture wounds.  First aid kits typically include items such as bandages, gauze, antiseptic wipes, and adhesive strips, allowing you to clean, dress, and protect wounds. This helps prevent infection, reduces pain, and accelerates the healing process.", type: "Protection" },
      { name: "Ice Axe", description: "For climbing icy surfaces.", image: "/images/ice_axe.jpg", details: "Ice axe for stability while climbing icy slopes. The ice axe is an essential tool for mountaineering and ice climbing. It is used for cutting steps in ice, anchoring the climber in place, and providing stability while traversing icy or snow-covered terrain. Provide extra stability and support when climbing or traversing steep, icy slopes. It allows climbers to maintain their balance and prevent slipping, especially when the surface is hard or compacted.", type: "Protection" },
      { name: "Headlamp", description: "Hands-free light source for night activities.", image: "/images/headlamp.jpg", details: "Provides light during nighttime hiking or climbing. Headlamp provides hands-free illumination, which is essential when you need both hands for tasks such as climbing, hiking, cooking, or setting up camp. It allows for better mobility and freedom to work in the dark without having to hold a flashlight. In an emergency, a headlamp can be a lifesaver, especially in low-light or completely dark environments. It helps you signal for help, navigate safely, or perform essential tasks without losing precious time. Its hands-free design makes it even more valuable during crisis situations.", type: "Protection" },
      { name: "Shovel", description: "For digging or clearing debris.", image: "/images/shovel.jpg", details: "Compact and lightweight shovel for emergency use. Shovel is primarily used for digging, whether it’s for creating holes, trenches, or clearing debris. In outdoor survival situations, it is invaluable for tasks like digging fire pits, latrines, or creating a shelter foundation. In winter conditions, a shovel is essential for digging out of snow, whether it’s for clearing paths or creating snow shelters like igloos or snow caves. It’s especially useful for avalanche rescue or digging out trapped gear.", type: "Protection" },
      { name: "Portable Cooking Stove", description: "Compact stove for cooking during outdoor activities.", image: "/images/portable_stove.jpg", details: "Portable stove to cook meals during mountain survival situations. Portable cooking stove allows you to cook meals anywhere, whether you’re camping, hiking, or picnicking. It provides a reliable cooking solution when you're away from a kitchen or traditional cooking appliances. These stoves are generally simple to set up and operate. They typically use fuel sources like propane, butane, or liquid fuel, and with just a few simple steps, you can have a cooking system ready to use in the outdoors.", type: "Cooking" },
      { name: "Trap Tent", description: "Tent are used to staying and protect from element.", image: "/images/trap_tent.jpg", details: "A trap tent provides essential shelter and protection from various environmental elements such as rain, wind, sun, or snow. It can be set up quickly and offers a temporary space to stay dry and protected in outdoor conditions, especially during camping or hiking trips. Trap tents are designed to be lightweight and compact, making them easy to carry in a backpack or on a vehicle for outdoor activities. They are generally easy to set up, even for beginners, and offer quick shelter when you need it most, without requiring extensive assembly or technical knowledge.", type: "Protection" },
      { name: "Avalanche Receiver", description: "Used for finding lost peoples.", image: "/images/avalanche_receiver.jpg", details: "An avalanche receiver is a critical piece of safety equipment used in avalanche-prone areas. It helps rescuers quickly locate individuals who are buried under snow after an avalanche, significantly increasing the chances of survival in a timely rescue operation.  Avalanche receivers are typically used in conjunction with avalanche transceivers. While a transceiver transmits a signal when activated, the receiver is designed to pick up the transmitted signal from the buried transceiver, guiding rescuers to the exact location of the individual. This two-way communication system ensures efficient and effective rescue operations.", type: "Protection" },
    ],
    cold: [
      { name: "Insulated Jacket", description: "Keeps you warm in freezing temperatures.", image: "/images/insulated_jacket.jpg", details: "Thick, insulated jacket with waterproof outer layer. Insulated jacket is designed to provide warmth in cold environments by trapping body heat. The insulation material, such as down, synthetic fibers, or fleece, creates a barrier that prevents heat from escaping, keeping you warm in low temperatures. The combination of insulation and weatherproofing keeps you warm while shielding you from wind, rain, or snow, making them ideal for outdoor adventures.", type: "Clothing" },
      { name: "Heated Gloves", description: "Keeps your hands warm in sub-zero conditions.", image: "/images/gloves.jpg", details: "Battery-operated gloves for warmth in cold conditions. Heated gloves are designed to provide consistent warmth in extremely cold conditions. They contain built-in heating elements powered by rechargeable batteries, which ensure that your hands remain warm even in freezing temperatures, preventing frostbite and cold-related discomfort. In cold conditions, keeping hands warm is not only about comfort but also safety. Cold hands can lead to reduced grip strength, slower reflexes, and difficulty in handling gear. Heated gloves help maintain optimal hand function, improving safety during winter sports, outdoor activities, or emergency situations.", type: "Clothing" },
      { name: "Ice Axe", description: "For climbing icy surfaces.", image: "/images/ice_axe.jpg", details: "For climbing in glaciers and icy slopes. The ice axe is an essential tool for mountaineering and ice climbing. It is used for cutting steps in ice, anchoring the climber in place, and providing stability while traversing icy or snow-covered terrain. Provide extra stability and support when climbing or traversing steep, icy slopes. It allows climbers to maintain their balance and prevent slipping, especially when the surface is hard or compacted.", type: "Protection" },
      { name: "Snowshoes", description: "For traveling over deep snow.", image: "/images/snow_boot.jpg", details: "Helps you move through deep snow easily. Snowshoes provide a larger surface area that helps distribute your weight over a wider area, preventing you from sinking into deep snow. This gives you better traction and stability, allowing you to walk more easily across snow-covered terrain, whether it's powder, slush, or compacted snow. Snowshoes help reduce the energy required to walk in snow, making it easier to cover longer distances or enjoy winter hiking, running, or exploring without tiring as quickly.", type: "Protection" },
      { name: "Poncho", description: "Light and waterproof for unexpected rain.", image: "/images/poncho.jpg", details: "Portable waterproof poncho for staying dry. Poncho provides quick and effective protection from rain, snow, or wind. Made from waterproof or water-resistant materials, it helps keep you dry and comfortable in adverse weather conditions, making it a practical choice for hiking, camping, or outdoor activities.  Beyond rain protection, a poncho can serve multiple purposes. It can be used as a ground tarp for sitting, sleeping, or keeping your gear dry, or as an emergency shelter when conditions worsen. Some ponchos are even designed with a hood that can be adjusted to provide additional protection.", type: "Protection" },
      { name: "Portable Cooking Stove", description: "Compact stove for hot meals in cold climates.", image: "/images/portable_stove.jpg", details: "Portable stove for cooking during cold climate survival. Portable cooking stove allows you to cook meals anywhere, whether you’re camping, hiking, or picnicking. It provides a reliable cooking solution when you're away from a kitchen or traditional cooking appliances. These stoves are generally simple to set up and operate. They typically use fuel sources like propane, butane, or liquid fuel, and with just a few simple steps, you can have a cooking system ready to use in the outdoors.", type: "Cooking" },
      { name: "Cord", description: "For rescue in cold.", image: "/images/cord.jpg", details: "A cord is an incredibly versatile tool with countless applications in survival situations, outdoor activities, or daily tasks. Its uses range from building shelters to creating traps or carrying loads, making it an essential item in any kit. Cord is invaluable for constructing temporary shelters by tying tarps, branches, or other materials together securely. It can also help stabilize tents or lean-tos in windy or harsh conditions.", type: "Protection" },
      { name: "Map", description: "For Navigation over deep snow.", image: "/images/map.jpg", details: "A map helps you understand your current location and find your way to a desired destination. It allows you to plan routes and avoid getting lost, especially in unfamiliar terrain. Maps provide detailed information about the geography, including elevations, water sources, trails, and obstacles. This knowledge is essential for planning safe and efficient routes through challenging terrain.", type: "Protection" },
      { name: "Battery", description: "For lighting fire and other things.", image: "/images/battery.jpg", details: "Batteries provide power for critical devices such as flashlights, GPS units, radios, headlamps, and emergency beacons, all of which can be lifesaving in survival situations. Batteries can assist in fire-starting by creating sparks when combined with steel wool, providing a secondary method to light fires in emergencies.", type: "Protection" },
    ],
    marine: [
      { name: "Life Jacket", description: "For safety near or in water.", image: "/images/life_jacket.jpg", details: "Adjustable life jacket for safety in marine environments. Life jacket is designed to keep you afloat in water, providing buoyancy and preventing drowning in case of an accident or unexpected immersion. It ensures that you remain on the surface of the water until help arrives or you can reach safety. Provide critical protection in emergency situations, such as a boat capsizing, falling off a dock, or unexpected water hazards. They significantly reduce the risk of drowning by keeping your head above water and allowing you to conserve energy while waiting for rescue or reaching the shore.", type: "Clothing" },
      { name: "Waterproof Phone Case", description: "Protects your phone from water damage.", image: "/images/phone_case.jpg", details: "Durable case to keep your phone safe while on the water. Waterproof phone case provides an effective barrier against water, protecting your phone from damage caused by rain, splashes, spills, or submersion. This is particularly important for those who use their phones outdoors or near water sources, such as when hiking, kayaking, or swimming. Phones that come into prolonged contact with water can suffer from internal corrosion, affecting their functionality and lifespan. A waterproof phone case helps prevent this by keeping moisture out, ensuring the long-term performance and health of your device.", type: "Protection" },
      { name: "Compass", description: "Helps with navigation at sea.", image: "/images/compass.jpg", details: "Traditional compass for navigation on the water. Compass is an essential tool for determining direction, especially when you are navigating in unfamiliar terrain. It helps you orient yourself and follow a specific course, whether you’re hiking, trekking, or exploring the wilderness. In a survival scenario or if you're lost, a compass can be a lifesaver. It enables you to find your bearings, orient a map, and navigate toward safety. It also allows you to keep a steady heading when visibility is poor, such as in fog, heavy snow, or thick woods.", type: "Protection" },
      { name: "Signal Flare", description: "For signaling distress in marine environments.", image: "/images/signal_flare.jpg", details: "Flare for signaling when lost at sea or stranded. Signal flare is primarily used to alert rescuers or nearby individuals of your location in an emergency situation. Whether you're lost, stranded, or in distress, a flare can send a visual signal that is visible from miles away, helping rescuers locate you more quickly. They are especially useful in low-light conditions, such as at night or during fog, heavy rain, or snowstorms. The bright, intense light from the flare cuts through the darkness or weather, making you more visible to search and rescue teams, helicopters, or boats.", type: "Protection" },
      { name: "Solar Lantern", description: "Recharges with sunlight for light in the dark.", image: "/images/solar_lantern.jpg", details: "Compact solar-powered lantern for night-time visibility. Solar lanterns are powered by sunlight, making them an environmentally friendly and renewable source of light. They do not rely on batteries or electricity, which reduces the consumption of non-renewable energy sources and minimizes environmental impact. They have built-in rechargeable batteries that store energy collected during the day from sunlight. This stored energy can be used to power the lantern at night, ensuring you have light without needing to constantly replace batteries or rely on a power outlet.", type: "Protection" },
      { name: "Fishing Kit", description: "Used for catching food at sea.", image: "/images/fishing_kit.jpg", details: "A fishing kit for survival at sea, including rods, hooks, and line. Fishing kit is designed to be compact and portable, making it easy to carry in a backpack or vehicle for outdoor adventures. Whether you're fishing on a remote lake, a river, or at the beach, a fishing kit ensures that you have all the essential tools in one place, ready for use whenever needed. In case of emergencies, having a fishing kit can be a lifesaver. If you find yourself in a survival situation or need to provide food in a remote location, a fishing kit can provide the tools needed to catch fish for sustenance.", type: "Protection" },
      { name: "Portable Cooking Stove", description: "For cooking at sea or coastal survival.", image: "/images/portable_stove.jpg", details: "A portable stove to cook meals while on the water or stranded at sea. Portable cooking stove allows you to cook meals anywhere, whether you’re camping, hiking, or picnicking. It provides a reliable cooking solution when you're away from a kitchen or traditional cooking appliances. These stoves are generally simple to set up and operate. They typically use fuel sources like propane, butane, or liquid fuel, and with just a few simple steps, you can have a cooking system ready to use in the outdoors.", type: "Cooking" },
      { name: "Hexamine Stove", description: "For cooking at sea.", image: "/images/hexamine_stove.jpg", details: "Hexamine stoves are small, portable, and lightweight, making them ideal for outdoor activities like hiking, camping, or backpacking. Their compact design ensures that they don’t take up much space in a pack, allowing for easy transport without adding significant weight to your gear. Hexamine stoves are simple to operate. You simply place the hexamine tablets on the stove’s surface, light them, and the stove will generate heat for cooking. There is no need for complicated setup or specialized knowledge, making them accessible for beginners and experienced outdoor enthusiasts alike.", type: "Cooking" },
      { name: "Whistle", description: "Alert others or signal distress.", image: "/images/whistle.jpg", details: "A loud whistle to attract attention in case of emergency. Whistle is an essential tool for signaling in emergency situations. Its loud, high-pitched sound can carry over long distances, making it easier to alert others to your presence or call for help.  whistles can be used for a variety of other purposes, such as attracting attention in a group setting, coordinating movement during team activities, or warning of potential dangers.", type: "Protection" },
    ],
  };
  
  

  const SurvivalKit = () => {
    const [selectedEnv, setSelectedEnv] = useState("tropical");
    const [selectedType, setSelectedType] = useState("All");
    const [isOverlayOpen, setIsOverlayOpen] = useState(false);
    const [overlayContent, setOverlayContent] = useState("");
  
    const handleEnvironmentChange = (event) => {
      setSelectedEnv(event.target.value);
    };
  
    const handleTypeChange = (event) => {
      setSelectedType(event.target.value);
    };
  
    const openOverlay = (details) => {
      setOverlayContent(details);
      setIsOverlayOpen(true);
    };
  
    const closeOverlay = () => {
      setIsOverlayOpen(false);
      setOverlayContent("");
    };
  
    const handleOverlayClick = (event) => {
      if (event.target.className === "overlay") {
        closeOverlay();
      }
    };
    // Filter kits by type
    const filteredKits = selectedType === "All"
      ? survivalKits[selectedEnv]
      : survivalKits[selectedEnv].filter(item => item.type === selectedType);
  
    return (
      <div className="survival-kit-container">
        <h2>Survival Kit for Different Environments</h2>
  
        <div className="selectors">
          <div className="environment-selector">
            <label htmlFor="environment">Select Environment:</label>
            <select id="environment" onChange={handleEnvironmentChange} value={selectedEnv}>
              <option value="tropical">Tropical</option>
              <option value="desert">Desert</option>
              <option value="mountain">Mountain</option>
              <option value="cold">Cold</option>
              <option value="marine">Marine</option>
            </select>
          </div>
  
          <div className="type-selector">
            <label htmlFor="type">Select Gear Type:</label>
            <select id="type" onChange={handleTypeChange} value={selectedType}>
              <option value="All">All</option>
              <option value="Protection">Protection</option>
              <option value="Clothing">Clothing</option>
              <option value="Cooking">Cooking</option>
            </select>
          </div>
        </div>
  
        <div className="kit-items">
          <h3>Recommended Gear for {selectedEnv.charAt(0).toUpperCase() + selectedEnv.slice(1)} Environment</h3>
          <div className="cards-container">
            {filteredKits.map((item, index) => (
              <div key={index} className="kit-card-container">
                <div className="kit-card">
                  <img src={item.image} alt={item.name} className="kit-card-image" />
                  <div className="kit-card-info">
                    <h4>{item.name}</h4>
                    <p>{item.description}</p>
                    <button className="view-details-btn" onClick={() => openOverlay(item.details)}>
                      View Details
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {isOverlayOpen && (
          <div className="overlay" onClick={handleOverlayClick}>
            <div className="overlay-content">
              <p>{overlayContent}</p>
              <button onClick={closeOverlay}>Close</button>
            </div>
          </div>
        )}
      </div>
    );
  };
  
  export default SurvivalKit;
